name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Build plugin
        run: yarn build

      - name: Sign plugin
        run: yarn run grafana-toolkit plugin:sign

      - name: Get plugin information
        run: |
          sudo apt-get install jq
          echo "GRAFANA_PLUGIN_ID=$(cat dist/plugin.json | jq -r .id)" >> $GITHUB_ENV
          echo "GRAFANA_PLUGIN_VERSION=$(cat dist/plugin.json | jq -r .info.version)" >> $GITHUB_ENV
          echo "GRAFANA_PLUGIN_ARTIFACT=${{ env.GRAFANA_PLUGIN_ID }}-${{ env.GRAFANA_PLUGIN_VERSION }}.zip" >> $GITHUB_ENV
          echo "GRAFANA_PLUGIN_ARTIFACT_CHECKSUM=${{ env.GRAFANA_PLUGIN_ID }}-${{ env.GRAFANA_PLUGIN_VERSION }}.zip.md5" >> $GITHUB_ENV

      - name: Package plugin
        run: |
          mv dist $GRAFANA_PLUGIN_ID
          zip $GRAFANA_PLUGIN_ARTIFACT $GRAFANA_PLUGIN_ID -r
          md5sum $GRAFANA_PLUGIN_ARTIFACT > $GRAFANA_PLUGIN_ARTIFACT_CHECKSUM
          ls
